### ISSUE TITLE
Add font-awesome styles to get Admonition symbols

### ISSUE THREAD

**Issue by jaredmorgs** [norganna/adoc-usermacro#2]
I know you were able to get the Foundation base styles into the macro, which look absolutely fantastic!

One thing that's missing is the admonition icons. In the Asciidoctor Foundation styles, these are not included by default.

You should be able to get them into the macro by referencing code from https://github.com/FortAwesome/Font-Awesome/blob/master/css/font-awesome.min.css 

Not sure if the min.css is the right thing to use, but if you poke around this repo, you should get what you need.

**Comment by jaredmorgs** [comment]
![screenshot 2015-09-03 09 29 01](https://cloud.githubusercontent.com/assets/952793/9647245/623560f6-521e-11e5-8f63-6abc5d67385f.png)
![screenshot 2015-09-03 09 29 40](https://cloud.githubusercontent.com/assets/952793/9647246/6238b2c4-521e-11e5-9210-b8943ad3a24b.png)

This gives you an idea about what the font-awesome symbols look like.

**Comment by norganna** [comment]
Done in ba5c7c2d4a39bdf80bed9cf6146145f4bd3f0e8a
